/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List warehouses (paged)
         * @description Returns a paged list of warehouses. Query params: page (default 1), pageSize (default 25, max 100), q (name contains, case-insensitive).
         */
        get: operations["listWarehouses"];
        put?: never;
        /**
         * Create warehouse
         * @description Creates a warehouse. Name and address are required; coordinates optional but range-validated.
         */
        post: operations["createWarehouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get warehouse by id */
        get: operations["getWarehouse"];
        /** Update warehouse (full update) */
        put: operations["updateWarehouse"];
        post?: never;
        /**
         * Delete warehouse
         * @description Hard delete in v1 (no soft-delete column). Later restricted once shipments reference warehouses.
         */
        delete: operations["deleteWarehouse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue access + refresh tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example LogiFlow */
            service: string;
            /**
             * Format: date-time
             * @example 2026-09-18T00:00:00Z
             */
            timestamp: string;
        };
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://logiflow.dev/errors/validation
             */
            type: string;
            /** @example Validation failed */
            title: string;
            /**
             * Format: int32
             * @example 400
             */
            status: number;
            detail?: string | null;
            errors?: {
                [key: string]: string[];
            };
            /** @example 00-abc123 */
            traceId?: string | null;
        };
        WarehouseRequest: {
            /** @example Central DC */
            name: string;
            /** @example 12 Industrial Rd, Rotterdam */
            address: string;
            /**
             * Format: double
             * @example 51.9244
             */
            latitude?: number;
            /**
             * Format: double
             * @example 4.4777
             */
            longitude?: number;
        };
        WarehouseResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example Central DC */
            name: string;
            /** @example 12 Industrial Rd */
            address: string;
            /**
             * Format: double
             * @example 51.9244
             */
            latitude?: number | null;
            /**
             * Format: double
             * @example 4.4777
             */
            longitude?: number | null;
            /**
             * Format: date-time
             * @example 2026-09-18T08:00:00Z
             */
            createdAt: string;
        };
        /** @description Envelope for all list endpoints (max pageSize 100, default 25). */
        PagedResponse: {
            /** @description Array of resource objects (schema defined per endpoint). */
            items: unknown[];
            /** @default 1 */
            page: number;
            /** @default 25 */
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
    };
    responses: {
        /** @description Validation failed */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized for this role/resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listWarehouses: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by name (contains, case-insensitive) */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged warehouse list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse"] & {
                        items?: components["schemas"]["WarehouseResponse"][];
                    };
                };
            };
        };
    };
    createWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            404: components["responses"]["ValidationProblem"];
        };
    };
    updateWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["ValidationProblem"];
        };
    };
    deleteWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ValidationProblem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example dana@logiflow.dev
                     */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        refresh_token?: string;
                        expires_in?: number;
                    };
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        expires_in?: number;
                    };
                };
            };
        };
    };
}
