/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Liveness probe used by CI, Playwright webServer readiness checks, and container orchestration.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List warehouses (paged)
         * @description Returns a paged list of warehouses. Query params: page (default 1), pageSize (default 25, max 100), q (name contains, case-insensitive).
         */
        get: operations["listWarehouses"];
        put?: never;
        /**
         * Create warehouse
         * @description Creates a warehouse. Name and address are required; coordinates optional but range-validated.
         */
        post: operations["createWarehouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Get warehouse by id
         * @description Returns a single warehouse. Responds 404 when the id does not exist.
         */
        get: operations["getWarehouse"];
        /**
         * Update warehouse (full update)
         * @description Replaces name, address and coordinates. Responds 404 when the id does not exist.
         */
        put: operations["updateWarehouse"];
        post?: never;
        /**
         * Delete warehouse
         * @description Hard delete in v1 (no soft-delete column). Later restricted once shipments reference warehouses.
         */
        delete: operations["deleteWarehouse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List vehicles (paged)
         * @description Returns a paged list of vehicles. Query params: page (default 1), pageSize (default 25, max 100), q (plate number contains, case-insensitive), status (Available/InRoute/Maintenance), type (Van/Truck/Trailer).
         */
        get: operations["listVehicles"];
        put?: never;
        /**
         * Create vehicle
         * @description Creates a vehicle. Plate number, type and a positive capacityKg are required; status defaults to Available. Duplicate plate numbers are rejected with 409.
         */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Get vehicle by id
         * @description Returns a single vehicle. Responds 404 when the id does not exist.
         */
        get: operations["getVehicle"];
        /**
         * Update vehicle (full update)
         * @description Replaces plate number, type, capacity and status. Responds 404 when the id does not exist, 409 when the plate number collides with another vehicle.
         */
        put: operations["updateVehicle"];
        post?: never;
        /**
         * Delete vehicle
         * @description Hard delete in v1 (no soft-delete column). Responds 409 when the vehicle is referenced by a route (routes arrive in LOGI-0009).
         */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List drivers (paged)
         * @description Returns a paged list of drivers. Query params: page (default 1), pageSize (default 25, max 100), q (full name contains, case-insensitive), status (Active/OffDuty/Suspended).
         */
        get: operations["listDrivers"];
        put?: never;
        /**
         * Create driver
         * @description Creates a driver. fullName and licenseNumber are required; status defaults to Active. licenseNumber must be unique (409). userId optionally links a login user account — the user must exist (400) and may be linked to at most one driver (409).
         */
        post: operations["createDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Get driver by id
         * @description Returns a single driver. Responds 404 when the id does not exist.
         */
        get: operations["getDriver"];
        /**
         * Update driver (full update)
         * @description Replaces full name, license number, phone, status and the optional user link. Responds 404 when the id does not exist, 409 when the license number collides with another driver or the target user is already linked to another driver.
         */
        put: operations["updateDriver"];
        post?: never;
        /**
         * Delete driver
         * @description Hard delete in v1 (no soft-delete column). Responds 409 when the driver is referenced by a route (routes arrive in LOGI-0009).
         */
        delete: operations["deleteDriver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipments/{id}/status-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition shipment status (BR-7 state machine)
         * @description Moves a shipment to toStatus and appends an immutable entry to the audit trail
         *     (shipment_status_history) in one transaction. BR-7 legal transitions only:
         *       Pending → Assigned → InTransit → Delivered
         *       Pending → Cancelled, Assigned → Cancelled
         *       InTransit → Delayed, Delayed → InTransit
         *     Any other transition is rejected with 409; the ProblemDetails detail names the
         *     legal next state(s). No history row is written for rejected attempts.
         *     Note: the Driver role is declared here per BR-6 (own-route shipments only);
         *     ownership scoping is enforced from LOGI-0009/0010.
         */
        post: operations["createShipmentStatusTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipments/{id}/status-history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * Shipment status audit trail (paged, oldest first)
         * @description Returns the append-only status history of a shipment ordered oldest → newest. Responds 404 when the shipment id does not exist.
         */
        get: operations["listShipmentStatusHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue access + refresh tokens
         * @description Authenticates an email/password pair and returns a short-lived access token plus a single-use refresh token. Anonymous endpoint. Invalid credentials return 401 without revealing whether the email exists (BR-driven anti-enumeration).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token
         * @description Exchanges a valid refresh token for a NEW access token and a NEW refresh token. The presented token is revoked in the same operation (rotation), so replaying it fails with 401. Anonymous endpoint — the refresh token itself is the credential.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Revokes the supplied refresh token so it can never be exchanged again. Idempotent from the caller's perspective: returns 204 and does not disclose whether the token existed.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current authenticated user
         * @description Returns the identity carried by the presented access token. Used by the SPA on start-up to restore session state and decide which UI affordances to render for the user's role.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example LogiFlow */
            service: string;
            /**
             * Format: date-time
             * @example 2026-09-18T00:00:00Z
             */
            timestamp: string;
        };
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://logiflow.dev/errors/validation
             */
            type: string;
            /** @example Validation failed */
            title: string;
            /**
             * Format: int32
             * @example 400
             */
            status: number;
            detail?: string | null;
            errors?: {
                [key: string]: string[];
            };
            /** @example 00-abc123 */
            traceId?: string | null;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example dana@logiflow.dev
             */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        /** @description Identity of an authenticated user. Never carries credential material (no hash, no stamp, no token). */
        AuthUser: {
            /**
             * Format: int64
             * @example 2
             */
            id: number;
            /**
             * Format: email
             * @example dana@logiflow.dev
             */
            email: string;
            /** @example Dana Doolittle */
            fullName: string;
            /**
             * @example Dispatcher
             * @enum {string}
             */
            role: "Admin" | "Dispatcher" | "Driver" | "Viewer";
        };
        TokenResponse: {
            /** @description Signed JWT bearer token (lifetime = expiresIn seconds). */
            accessToken: string;
            /** @description Opaque, single-use rotating refresh token. Consumed and replaced by POST /auth/refresh. */
            refreshToken: string;
            /**
             * Format: int32
             * @description Access token lifetime in seconds.
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["AuthUser"];
        };
        WarehouseRequest: {
            /** @example Central DC */
            name: string;
            /** @example 12 Industrial Rd, Rotterdam */
            address: string;
            /**
             * Format: double
             * @example 51.9244
             */
            latitude?: number;
            /**
             * Format: double
             * @example 4.4777
             */
            longitude?: number;
        };
        WarehouseResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example Central DC */
            name: string;
            /** @example 12 Industrial Rd */
            address: string;
            /**
             * Format: double
             * @example 51.9244
             */
            latitude?: number | null;
            /**
             * Format: double
             * @example 4.4777
             */
            longitude?: number | null;
            /**
             * Format: date-time
             * @example 2026-09-18T08:00:00Z
             */
            createdAt: string;
        };
        VehicleRequest: {
            /** @example RT-8421-X */
            plateNumber: string;
            /**
             * @example Truck
             * @enum {string}
             */
            type: "Van" | "Truck" | "Trailer";
            /**
             * Format: double
             * @example 12000
             */
            capacityKg: number;
            /**
             * @default Available
             * @example Available
             * @enum {string}
             */
            status: "Available" | "InRoute" | "Maintenance";
        };
        VehicleResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example RT-8421-X */
            plateNumber: string;
            /**
             * @example Truck
             * @enum {string}
             */
            type: "Van" | "Truck" | "Trailer";
            /**
             * Format: double
             * @example 12000
             */
            capacityKg: number;
            /**
             * @example Available
             * @enum {string}
             */
            status: "Available" | "InRoute" | "Maintenance";
            /**
             * Format: date-time
             * @example 2026-09-20T00:00:00Z
             */
            createdAt: string;
        };
        DriverRequest: {
            /** @example Raj Patil */
            fullName: string;
            /** @example DL-112-4589 */
            licenseNumber: string;
            /** @example +31 6 1234 5678 */
            phone?: string;
            /**
             * @default Active
             * @example Active
             * @enum {string}
             */
            status: "Active" | "OffDuty" | "Suspended";
            /**
             * Format: int64
             * @description Optional link to a login user account (users.id). The user must exist and may be linked to at most one driver (User 1---1 Driver).
             * @example 7
             */
            userId?: number;
        };
        /** @description Driver master data. Deliberately carries no createdAt — the approved schema §drivers defines no created_at column. */
        DriverResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /**
             * Format: int64
             * @example 7
             */
            userId?: number | null;
            /** @example Raj Patil */
            fullName: string;
            /** @example DL-112-4589 */
            licenseNumber: string;
            /** @example +31 6 1234 5678 */
            phone?: string | null;
            /**
             * @example Active
             * @enum {string}
             */
            status: "Active" | "OffDuty" | "Suspended";
        };
        /** @description Body of POST /shipments/{id}/status-transitions. Legal transitions only (BR-7) — illegal transitions are rejected server-side with 409. */
        StatusTransitionRequest: {
            /**
             * @example Assigned
             * @enum {string}
             */
            toStatus: "Pending" | "Assigned" | "InTransit" | "Delivered" | "Delayed" | "Cancelled";
            /**
             * @description Optional free-text reason recorded in the audit trail.
             * @example Loaded onto vehicle RT-8421-X
             */
            note?: string | null;
        };
        /** @description One entry of the shipment audit trail (shipment_status_history). Immutable, append-only. */
        ShipmentStatusEvent: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /**
             * @description null on the initial entry.
             * @example Pending
             * @enum {string|null}
             */
            fromStatus?: "Pending" | "Assigned" | "InTransit" | "Delivered" | "Delayed" | "Cancelled" | null;
            /**
             * @example Assigned
             * @enum {string}
             */
            toStatus: "Pending" | "Assigned" | "InTransit" | "Delivered" | "Delayed" | "Cancelled";
            /**
             * Format: int64
             * @example 7
             */
            changedByUserId: number;
            /**
             * Format: date-time
             * @example 2026-09-22T08:00:00Z
             */
            changedAt: string;
            /** @example Loaded onto vehicle RT-8421-X */
            note?: string | null;
        };
        /** @description Envelope for all list endpoints (max pageSize 100, default 25). */
        PagedResponse: {
            /** @description Array of resource objects (schema defined per endpoint). */
            items: unknown[];
            /** @default 1 */
            page: number;
            /** @default 25 */
            pageSize: number;
            totalCount: number;
            totalPages: number;
        };
    };
    responses: {
        /** @description Validation failed */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but not authorized for this role/resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Conflicting state — e.g. a unique constraint violation or a referenced resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listWarehouses: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by name (contains, case-insensitive) */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged warehouse list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse"] & {
                        items?: components["schemas"]["WarehouseResponse"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listVehicles: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by plate number (contains, case-insensitive) */
                q?: string;
                /** @description Filter by status */
                status?: "Available" | "InRoute" | "Maintenance";
                /** @description Filter by vehicle type */
                type?: "Van" | "Truck" | "Trailer";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged vehicle list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse"] & {
                        items?: components["schemas"]["VehicleResponse"][];
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listDrivers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by full name (contains, case-insensitive) */
                q?: string;
                /** @description Filter by status */
                status?: "Active" | "OffDuty" | "Suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged driver list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse"] & {
                        items?: components["schemas"]["DriverResponse"][];
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDriver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createShipmentStatusTransition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusTransitionRequest"];
            };
        };
        responses: {
            /** @description Transitioned — the recorded audit event is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentStatusEvent"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listShipmentStatusHistory: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged history (oldest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponse"] & {
                        items?: components["schemas"]["ShipmentStatusEvent"][];
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Tokens issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued; the presented refresh token is revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh token revoked (or already unusable) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user's identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
